name: Python CDK Synthesis on Pull Request

on:
  pull_request:
    branches:
      - master  # Replace with your branch name

jobs:
  synthesize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Node.js version for CDK

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk  # Install the AWS CDK globally
          echo "CDK installed successfully."
          which cdk  # Locate where the cdk binary is installed
          cdk --version  # Verify CDK installation

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug PATH
        run: echo $PATH  # Check the PATH environment variable to ensure it includes the npm global bin directory

      - name: Bootstrap CDK
        run: cdk bootstrap  # Bootstrap the environment
