name: PR Deployment Check

on:
  pull_request:
    branches:
      - master

jobs:
  validate-cdk:
    name: Validate CDK App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Node.js (for CDK CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Install Python CDK and Dependencies
        run: |
          pip install aws-cdk-lib constructs
          pip install -r requirements.txt

      - name: Bootstrap CDK Environment
        run: cdk bootstrap

      - name: Synthesize CDK App
        run: cdk synth

      - name: Diff Against Deployed Stack
        run: cdk diff
